# Parameters for Robotont.

# Serial connection
serial:
  port: "/dev/ttyACM0"
  baudrate: 115200
  # baudrate: 256000

# Frame names for odometry
odom:
  frame: $(arg prefix)odom
  child_frame: $(arg prefix)base_footprint

